version: '3.1'

services:
  web:
    container_name: ng
    build: .
    expose:
     - 80
    ports:
     - 80:80
    volumes:
      - $PWD/html:/var/www/html
      - $PWD/log/nginx:/var/log/nginx
      - $PWD/conf:/etc/nginx/sites-avaible