version: '3.1'

services:
  web:
    container_name: ng
    build: .
    expose:
     - 80 #defaul
     - 8010 #newsite
     - 8020 #laravel
    # ports:
    #  - 80:80
    volumes:
      # Volumnes para el control del sitio
      # El proyecto que trabajes debe estar en un servidor en la ruta /var/www/html/sitio
      - /var/www/html:/var/www/html
      - /var/www/html/newsite:/var/www/html/newsite
      - /var/www/html/laravel:/var/www/html/laravel
      - $PWD/log/nginx:/var/log/nginx
      - $PWD/conf:/etc/nginx/sites-available
    network_mode: "host"
